// Generated by Lux — `lux types`. Do not edit by hand.

export type Json = string | number | boolean | null | Json[] | { [key: string]: Json };

export interface Messages {
    attachments: Json | null;
    content: string | null;
    created_at: number | null;
    dispatch_id: string | null;
    id: number;
    medium: string | null;
    metadata: Json | null;
    role: string | null;
    type: string | null;
}

export interface Compaction {
    created_at: number | null;
    id: string;
    summary: string | null;
    through_at: number | null;
}

export interface Memories {
    body: string | null;
    category: string | null;
    created_at: number | null;
    embedding: number[] | null;
    id: string;
    last_used_at: number | null;
    type: string | null;
    use_count: number | null;
}

export interface Dispatches {
    activities: Json | null;
    created_at: number | null;
    id: string;
    status: string | null;
    streaming_text: string | null;
    updated_at: number | null;
}

export interface McpConnections {
    id: string;
    name: string | null;
    url: string | null;
    transport: string | null;
    auth: Json | null;
    config: Json | null;
    disabled: boolean | null;
    created_at: number | null;
}

export interface Settings {
    key: string;
    value: string | null;
    updated_at: number | null;
}

export interface Devices {
    id: string;
    name: string | null;
    kind: string | null;
    screen_w: number | null;
    screen_h: number | null;
    connected: boolean | null;
    last_seen: number | null;
    created_at: number | null;
}

export interface Presence {
    id: string;
    device_id: string | null;
    updated_at: number | null;
}

export interface Panels {
    id: string;
    device_id: string | null;
    title: string | null;
    x: number | null;
    y: number | null;
    w: number | null;
    h: number | null;
    z: number | null;
    components: Json | null;
    state: Json | null;
    status: string | null;
    created_at: number | null;
    updated_at: number | null;
}

export type Database = {
    messages: Messages;
    compaction: Compaction;
    memories: Memories;
    dispatches: Dispatches;
    mcp_connections: McpConnections;
    settings: Settings;
    devices: Devices;
    presence: Presence;
    panels: Panels;
};
