// Generated by Lux — `lux types`. Do not edit by hand.

export type Json = string | number | boolean | null | Json[] | { [key: string]: Json };

export interface Messages {
    attachments: Json | null;
    content: string | null;
    created_at: number | null;
    dispatch_id: string | null;
    id: number;
    medium: string | null;
    metadata: Json | null;
    role: string | null;
    type: string | null;
}

export interface Compaction {
    created_at: number | null;
    id: string;
    summary: string | null;
    through_at: number | null;
}

export interface Memories {
    body: string | null;
    category: string | null;
    created_at: number | null;
    embedding: number[] | null;
    id: string;
    last_used_at: number | null;
    type: string | null;
    use_count: number | null;
}

export interface Dispatches {
    activities: Json | null;
    created_at: number | null;
    id: string;
    status: string | null;
    streaming_text: string | null;
    updated_at: number | null;
}

export interface McpConnections {
    auth: Json | null;
    config: Json | null;
    created_at: number | null;
    disabled: boolean | null;
    id: string;
    name: string | null;
    transport: string | null;
    url: string | null;
}

export interface Settings {
    key: string;
    updated_at: number | null;
    value: string | null;
}

export interface Devices {
    connected: boolean | null;
    created_at: number | null;
    id: string;
    kind: string | null;
    last_seen: number | null;
    name: string | null;
    screen_h: number | null;
    screen_w: number | null;
}

export interface Presence {
    device_id: string | null;
    id: string;
    updated_at: number | null;
}

export interface Panels {
    components: Json | null;
    created_at: number | null;
    device_id: string | null;
    functions: Json | null;
    h: number | null;
    id: string;
    maximized: boolean | null;
    state: Json | null;
    status: string | null;
    title: string | null;
    updated_at: number | null;
    w: number | null;
    x: number | null;
    y: number | null;
    z: number | null;
}

export interface Secrets {
    created_at: number | null;
    description: string | null;
    is_placeholder: boolean | null;
    key: string;
    updated_at: number | null;
    value: string | null;
}

export interface Questions {
    answer: Json | null;
    answers: Json | null;
    created_at: number | null;
    dispatch_id: string | null;
    header: string | null;
    id: string;
    items: Json | null;
    multi: boolean | null;
    options: Json | null;
    question: string | null;
    status: string | null;
    updated_at: number | null;
}

export interface MediumActivity {
    body: string | null;
    created_at: number | null;
    error: string | null;
    id: string;
    medium: string | null;
    status: string | null;
    title: string | null;
    urgency: string | null;
}

export interface Projects {
    budget_usd: number | null;
    created_at: number | null;
    device_id: string | null;
    error: string | null;
    est_cost_usd: number | null;
    goal: string | null;
    id: string;
    model: string | null;
    parent_dispatch_id: string | null;
    result: string | null;
    spent_usd: number | null;
    status: string | null;
    title: string | null;
    updated_at: number | null;
}

export interface ProjectTasks {
    activities: Json | null;
    cost_usd: number | null;
    created_at: number | null;
    depends_on: Json | null;
    description: string | null;
    id: string;
    idx: number | null;
    input_tokens: number | null;
    job_id: string | null;
    output_tokens: number | null;
    project_id: string | null;
    result: string | null;
    status: string | null;
    streaming_text: string | null;
    title: string | null;
    tools: Json | null;
    updated_at: number | null;
}

export type Database = {
    messages: Messages;
    compaction: Compaction;
    memories: Memories;
    dispatches: Dispatches;
    mcp_connections: McpConnections;
    settings: Settings;
    devices: Devices;
    presence: Presence;
    panels: Panels;
    secrets: Secrets;
    questions: Questions;
    medium_activity: MediumActivity;
    projects: Projects;
    project_tasks: ProjectTasks;
};
