/**
 * Everything under ~/.nero — the stack's home. The CLI owns the compose file
 * (regenerated, managed) but treats `.env` as SACRED: it only ever APPENDS
 * missing keys, never edits or removes what's already there.
 */
import { homedir } from 'os';
import { join } from 'path';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { randomBytes } from 'crypto';

export const HOME = join(homedir(), '.nero');
export const ENV_PATH = join(HOME, '.env');
export const COMPOSE_PATH = join(HOME, 'docker-compose.yml');

/** Image tags the generated compose pulls. */
const IMG_API = process.env.NERO_API_IMAGE || 'ghcr.io/pompeii-labs/nero-api:latest';
const IMG_WEB = process.env.NERO_WEB_IMAGE || 'ghcr.io/pompeii-labs/nero-web:latest';
const IMG_LUX = process.env.NERO_LUX_IMAGE || 'ghcr.io/lux-db/lux:latest';

export function ensureHome(): void {
    if (!existsSync(HOME)) mkdirSync(HOME, { recursive: true });
}

/** Parse ~/.nero/.env into a flat map (ignores comments / blanks). */
export function readEnv(): Record<string, string> {
    if (!existsSync(ENV_PATH)) return {};
    const out: Record<string, string> = {};
    for (const raw of readFileSync(ENV_PATH, 'utf8').split('\n')) {
        const l = raw.trim();
        if (!l || l.startsWith('#')) continue;
        const i = l.indexOf('=');
        if (i < 0) continue;
        out[l.slice(0, i).trim()] = l
            .slice(i + 1)
            .trim()
            .replace(/^["']|["']$/g, '');
    }
    return out;
}

/** Load ~/.nero/.env into process.env (without overriding already-set vars), so
 *  Lux-touching commands (mcp, config, doctor) read the right connection. */
export function loadHomeEnv(): void {
    for (const [k, v] of Object.entries(readEnv())) {
        if (process.env[k] === undefined) process.env[k] = v;
    }
}

/** Append only the keys not already present. Never touches existing lines. */
export function appendEnv(additions: Record<string, string>, banner?: string): string[] {
    ensureHome();
    const current = readEnv();
    const missing = Object.entries(additions).filter(([k]) => !(k in current));
    if (missing.length === 0) return [];
    const block =
        (existsSync(ENV_PATH) && readFileSync(ENV_PATH, 'utf8').length ? '\n' : '') +
        (banner ? `# ${banner}\n` : '') +
        missing.map(([k, v]) => `${k}=${v}`).join('\n') +
        '\n';
    writeFileSync(ENV_PATH, (existsSync(ENV_PATH) ? readFileSync(ENV_PATH, 'utf8') : '') + block);
    return missing.map(([k]) => k);
}

const key = (prefix: string) => `${prefix}${randomBytes(24).toString('hex')}`;

export type LuxMode = 'bundled' | 'external';

/** Bundled unless the user pointed LUX_URL at something that isn't our engine. */
export function luxMode(env = readEnv()): LuxMode {
    const url = env.LUX_URL;
    if (!url) return 'bundled';
    return url.includes('@lux:') ? 'bundled' : 'external';
}

/**
 * Make sure the env has what the stack needs. Generates Lux creds for the
 * bundled engine on first run (persisted to .env). Returns the keys it added.
 */
export function ensureStackEnv(): string[] {
    const env = readEnv();
    if (luxMode(env) === 'external') return [];

    const secret = env.LUX_SECRET_KEY || key('lux_sec_local_');
    const pub = env.LUX_PUBLISHABLE_KEY || key('lux_pub_local_');
    return appendEnv(
        {
            LUX_SECRET_KEY: secret,
            LUX_PUBLISHABLE_KEY: pub,
            // api -> engine over the compose network (operator: Bearer == password)
            LUX_URL: `lux://:${secret}@lux:6379`,
            // browser -> engine, host-reachable (served to the SPA via /v1/config)
            NERO_PUBLIC_LUX_URL: 'http://localhost:8080',
        },
        'Bundled Lux engine (auto-generated; safe to leave)',
    );
}

/** Render the managed docker-compose.yml for the current env. */
export function renderCompose(env = readEnv()): string {
    const bundled = luxMode(env) === 'bundled';
    const lux = bundled
        ? `  lux:
    image: ${IMG_LUX}
    restart: unless-stopped
    environment:
      LUX_AUTH_ENABLED: "1"
      LUX_AUTH_PASSWORD: "\${LUX_SECRET_KEY}"
      LUX_AUTH_SECRET_KEY: "\${LUX_SECRET_KEY}"
      LUX_AUTH_PUBLISHABLE_KEY: "\${LUX_PUBLISHABLE_KEY}"
      LUX_PORT: "6379"
      LUX_HTTP_PORT: "8080"
      LUX_BIND_HOST: "0.0.0.0"
      LUX_DATA_DIR: /data
      LUX_STORAGE_MODE: tiered
      LUX_STORAGE_DIR: /data/storage
    volumes:
      - lux-data:/data
    ports:
      - "8080:8080"
`
        : '';
    const apiDeps = bundled ? '\n    depends_on: [lux]' : '';

    return `# Generated by the nero CLI — managed file. Configure via ~/.nero/.env
name: nero
services:
${lux}  api:
    image: ${IMG_API}
    restart: unless-stopped
    env_file: [.env]${apiDeps}
    expose: ["4848"]
  web:
    image: ${IMG_WEB}
    restart: unless-stopped
    depends_on: [api]
    ports:
      - "\${NERO_PORT:-4848}:80"
${bundled ? 'volumes:\n  lux-data:\n' : ''}`;
}

/** Write the managed compose file (always regenerated). */
export function writeCompose(env = readEnv()): void {
    ensureHome();
    writeFileSync(COMPOSE_PATH, renderCompose(env));
}
