name: Nero
options:
  bundleIdPrefix: com.pompeiilabs
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    CLANG_CXX_LANGUAGE_STANDARD: gnu++20
    CLANG_ENABLE_MODULES: YES
    ENABLE_USER_SCRIPT_SANDBOXING: YES

targets:
  Nero:
    type: application
    platform: iOS
    sources:
      - path: Nero
    configFiles:
      Debug: Signing.xcconfig
      Release: Signing.xcconfig
    settings:
      base:
        INFOPLIST_FILE: Nero/Info.plist
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Nero
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
        INFOPLIST_KEY_NSMicrophoneUsageDescription: Nero needs microphone access for voice conversations
        INFOPLIST_KEY_NSLocalNetworkUsageDescription: Nero needs local network access to connect to your Nero server
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        MARKETING_VERSION: "1.29.0"
        CURRENT_PROJECT_VERSION: 1
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_EMIT_LOC_STRINGS: YES
      debug:
        DEBUG_INFORMATION_FORMAT: dwarf
        ENABLE_TESTABILITY: YES
        GCC_OPTIMIZATION_LEVEL: "0"
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG $(inherited)"
        MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
        ONLY_ACTIVE_ARCH: YES
      release:
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        ENABLE_NS_ASSERTIONS: NO
        SWIFT_COMPILATION_MODE: wholemodule
        VALIDATE_PRODUCT: YES
        MTL_ENABLE_DEBUG_INFO: NO
